/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Person;
import Model.personDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author saitarunreddylakkireddy
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    personDirectory log;
    
    
    
    public MainJFrame() {
        initComponents(); 
        log=new personDirectory();
     
        populateStartupData();
    
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitpane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDirectory = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblProfile = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitpane.setDividerLocation(200);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnAdd.setText("Add Perosn");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDirectory.setText("List Person");
        btnDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectoryActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        lblProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfile.setText("PersonProfile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDirectory});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSearch, txtSearch});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblProfile)
                .addGap(74, 74, 74)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDirectory)
                .addGap(90, 90, 90)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnDirectory});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSearch, txtSearch});

        splitpane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );

        splitpane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitpane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitpane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        PersonJPanel create = new PersonJPanel(log);
        splitpane.setRightComponent(create);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String Search = txtSearch.getText();
        Person result = log.searchPerson(txtSearch.getText());
        if (result == null){
            JOptionPane.showMessageDialog(null, "Details do not match with existing profiles.", "Information", JOptionPane.INFORMATION_MESSAGE);
            
        }
        else {
        SearchJPanel panel = new SearchJPanel(log,Search);
        splitpane.setRightComponent(panel);
           
                
        }

        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectoryActionPerformed
        // TODO add your handling code here:
        
        
        PersonLogJPanel view =new PersonLogJPanel(log);
        splitpane.setRightComponent(view);
             
        
    }//GEN-LAST:event_btnDirectoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDirectory;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JSplitPane splitpane;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void populateStartupData() {
    
        
        Person p1 = log.addNewPerson();
    p1.setFirstName("Andy");
    p1.setLastName("King");
    p1.setSocialSecurityNumber("22327789");
    p1.setLicenseNumber("23653");
    p1.getHomeAddress().setStreet("abc");
    p1.getHomeAddress().setUnitNumber("1");
    p1.getHomeAddress().setCity("Bos");
    p1.getHomeAddress().setState("MA");
    p1.getHomeAddress().setZipCode("02120");
    p1.getWorkAddress().setStreet("xyz");
    p1.getWorkAddress().setUnitNumber("1");
    p1.getWorkAddress().setCity("Hyd");
    p1.getWorkAddress().setState("TS");
    p1.getWorkAddress().setZipCode("34555");
    
    
      Person p2 = log.addNewPerson();  
    p2.setFirstName("Jon");
    p2.setLastName("Snow");
    p2.setSocialSecurityNumber("22327790");
    p2.setLicenseNumber("23634");
    p2.getHomeAddress().setStreet("poi");
    p2.getHomeAddress().setUnitNumber("9");
    p2.getHomeAddress().setCity("Bos");
    p2.getHomeAddress().setState("MA");
    p2.getHomeAddress().setZipCode("02122");
    p2.getWorkAddress().setStreet("gfh");
    p2.getWorkAddress().setUnitNumber("7");
    p2.getWorkAddress().setCity("Hyd");
    p2.getWorkAddress().setState("TS");
    p2.getWorkAddress().setZipCode("34675");
    
    
     Person p3 = log.addNewPerson();  
    p3.setFirstName("John");
    p3.setLastName("wick");
    p3.setSocialSecurityNumber("22323490");
    p3.setLicenseNumber("43634");
    p3.getHomeAddress().setStreet("dfg");
    p3.getHomeAddress().setUnitNumber("4");
    p3.getHomeAddress().setCity("Bos");
    p3.getHomeAddress().setState("MA");
    p3.getHomeAddress().setZipCode("05122");
    p3.getWorkAddress().setStreet("bgh");
    p3.getWorkAddress().setUnitNumber("7");
    p3.getWorkAddress().setCity("Hyd");
    p3.getWorkAddress().setState("TS");
    p3.getWorkAddress().setZipCode("51675");
    
    Person p4 = log.addNewPerson();  
    p4.setFirstName("Daenerys");
    p4.setLastName("Targareyn");
    p4.setSocialSecurityNumber("908886490");
    p4.setLicenseNumber("43123");
    p4.getHomeAddress().setStreet("qqa");
    p4.getHomeAddress().setUnitNumber("5");
    p4.getHomeAddress().setCity("Bos");
    p4.getHomeAddress().setState("MA");
    p4.getHomeAddress().setZipCode("31222");
    p4.getWorkAddress().setStreet("bgd");
    p4.getWorkAddress().setUnitNumber("10");
    p4.getWorkAddress().setCity("Vja");
    p4.getWorkAddress().setState("AP");
    p4.getWorkAddress().setZipCode("52134");
    
    Person p5 = log.addNewPerson();  
    p5.setFirstName("Sam");
    p5.setLastName("Altman");
    p5.setSocialSecurityNumber("908126490");
    p5.setLicenseNumber("12323");
    p5.getHomeAddress().setStreet("hib");
    p5.getHomeAddress().setUnitNumber("6");
    p5.getHomeAddress().setCity("SF");
    p5.getHomeAddress().setState("CA");
    p5.getHomeAddress().setZipCode("31222");
    p5.getWorkAddress().setStreet("bgd");
    p5.getWorkAddress().setUnitNumber("10");
    p5.getWorkAddress().setCity("Vja");
    p5.getWorkAddress().setState("AP");
    p5.getWorkAddress().setZipCode("52134");
    
    
    }
}
