/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ucode.Business;
import ucode.CourseSchedule.CourseOffer;
import ucode.profiles.StudentProfile;

/**
 *
 * @author srimanth
 *
 */
public class CourseWorkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseWorkJPanel
     */
    JPanel CardSequencePanel;
    Business business;

    CourseOffer selectedCourseOffer;
    StudentProfile sp;

    public CourseWorkJPanel(Business bz, StudentProfile student, JPanel jp) {
        business = bz;
        CardSequencePanel = jp;
        sp = student;
        initComponents();
        refreshTable();
    }

    void refreshTable() {

        int rc = tbCourses.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tbCourses.getModel()).removeRow(i);
        }

        for (String sem : business.getSems()) {
            ArrayList<CourseOffer> coList = business.getCourseSchedule(sem).getCourseSchedule();

            for (CourseOffer co : coList) {
                if (co.findRegisteredStudent(sp) == null) {
                    continue;
                }
                Object[] row = new Object[5];
                row[0] = co; //.getAssociatedPersonProfile().getPerson().getName();
                row[1] = co.getCourseNumber();
                row[2] = co.getCourse().getFacultyProfile(); //ua.getAssociatedPersonProfile().getPerson().getName();
                row[3] = co.getCreditHours(); //ua.getRole();
                row[4] = sem; // business.getCourseRatings(co.getCourseNumber());
                ((DefaultTableModel) tbCourses.getModel()).addRow(row);
            }
        }

        //selectedCourseOffer = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCourses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        btnRate = new javax.swing.JButton();
        txtRating = new javax.swing.JTextField();
        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        tbCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Number", "professor", "credits", "Sem"
            }
        ));
        tbCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbCoursesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbCourses);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 790, 280);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CourseWork");
        add(jLabel1);
        jLabel1.setBounds(150, 0, 510, 40);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 380, 72, 23);


        btnRate.setText("rate course");
        btnRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRateActionPerformed(evt);
            }
        });
        add(btnRate);
        btnRate.setBounds(580, 370, 100, 23);

        txtRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatingActionPerformed(evt);
            }
        });
        add(txtRating);
        txtRating.setBounds(460, 370, 100, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void tbCoursesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCoursesMousePressed
        // TODO add your handling code here:
        // Extracts the row (uaser account) in the table that is selected by the user

        int size = tbCourses.getRowCount();
        int selectedrow = tbCourses.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selectedCourseOffer = (CourseOffer) tbCourses.getValueAt(selectedrow, 0);
        if (selectedCourseOffer == null) {
            return;

        }
    }//GEN-LAST:event_tbCoursesMousePressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    private void btnRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRateActionPerformed
        // TODO add your handling code here:
        if (selectedCourseOffer == null) {
            JOptionPane.showMessageDialog(this, "please select a course!");
            return;
        }
        selectedCourseOffer.setRating(Double.parseDouble(txtRating.getText()));
        JOptionPane.showMessageDialog(this, "course rated successfully");
    }//GEN-LAST:event_btnRateActionPerformed

    private void txtRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCourses;
    private javax.swing.JTextField txtRating;
    // End of variables declaration//GEN-END:variables
}
