/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ucode.Business;
import ucode.CourseSchedule.CourseOffer;
import ucode.profiles.StudentProfile;

/**
 *

 * @author srimanth

 */
public class TranscriptJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TranscriptJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    //CourseOffer selectedCourseOffer;
    StudentProfile sp;

    public TranscriptJPanel(Business bz, StudentProfile student, JPanel jp) {
        business = bz;
        CardSequencePanel = jp;
        sp = student;
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCourses = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        txtGpa = new javax.swing.JTextField();
        lblGpa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transcript");
        add(jLabel1);
        jLabel1.setBounds(160, 0, 330, 70);

        tbCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Number", "Grade", "credits", "Semester"
            }
        ));
        tbCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbCoursesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbCourses);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 640, 230);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 380, 72, 23);

        txtGpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGpaActionPerformed(evt);
            }
        });
        add(txtGpa);
        txtGpa.setBounds(450, 312, 90, 30);

        lblGpa.setText("GPA");
        add(lblGpa);
        lblGpa.setBounds(380, 320, 41, 16);
    }// </editor-fold>//GEN-END:initComponents
void refreshTable() {

        txtGpa.setText(String.valueOf(sp.getTranscript().GetTotalStudentScore()));
        int rc = tbCourses.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tbCourses.getModel()).removeRow(i);
        }

        for (String sem : business.getSems()) {
            ArrayList<CourseOffer> coList = business.getCourseSchedule(sem).getCourseSchedule();

            for (CourseOffer co : coList) {
                if (co.findRegisteredStudent(sp) == null) {
                    continue;
                }
                Object[] row = new Object[5];
                row[0] = co; //.getAssociatedPersonProfile().getPerson().getName();
                row[1] = co.getCourseNumber();
                row[2] = sp.getTranscript().GetCourseStudentScore(co);//co.getCourse().getFacultyProfile(); //ua.getAssociatedPersonProfile().getPerson().getName();
                row[3] = co.getCreditHours(); //ua.getRole();
                row[4] = sem; // business.getCourseRatings(co.getCourseNumber());
                ((DefaultTableModel) tbCourses.getModel()).addRow(row);
            }
        }
    }
    private void tbCoursesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCoursesMousePressed
        // TODO add your handling code here:
        // Extracts the row (uaser account) in the table that is selected by the user
        //        int size = tbCourses.getRowCount();
        //        int selectedrow = tbCourses.getSelectionModel().getLeadSelectionIndex();
        //
        //        if (selectedrow < 0 || selectedrow > size - 1) {
        //            return;
        //        }
        //        selectedCourseOffer = (CourseOffer) tbCourses.getValueAt(selectedrow, 0);
        //        if (selectedCourseOffer == null) {
        //            return;
        //
        //        }
    }//GEN-LAST:event_tbCoursesMousePressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGpaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JTable tbCourses;
    private javax.swing.JTextField txtGpa;
    // End of variables declaration//GEN-END:variables
}
