/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.BankDLog;
import model.HomeAddressLog;
import model.LocalAddressLog;
import model.NameLog;

/**
 *
 * @author saitarunreddylakkireddy
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    NameLog log;
    HomeAddressLog halog;
    LocalAddressLog lalog;
    BankDLog register;
    
    
    
    public MainJFrame() {
        initComponents();
        log = new NameLog();
        halog = new HomeAddressLog();
        lalog = new LocalAddressLog();
        register = new BankDLog();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreateN = new javax.swing.JButton();
        btnViewN = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnCreateHA = new javax.swing.JButton();
        btnViewHA = new javax.swing.JButton();
        btnCreateLA = new javax.swing.JButton();
        btnViewLA = new javax.swing.JButton();
        btnCreateBA = new javax.swing.JButton();
        btnViewBA = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(200);

        controlPanel.setBackground(new java.awt.Color(255, 204, 204));

        btnCreateN.setText("Create Name");
        btnCreateN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNActionPerformed(evt);
            }
        });

        btnViewN.setText("View Person");
        btnViewN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Person Profile");

        btnCreateHA.setText("Create Home Address");
        btnCreateHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHAActionPerformed(evt);
            }
        });

        btnViewHA.setText("View Home Address");
        btnViewHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHAActionPerformed(evt);
            }
        });

        btnCreateLA.setText("Create Local Address");
        btnCreateLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLAActionPerformed(evt);
            }
        });

        btnViewLA.setText("View Local Address");
        btnViewLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLAActionPerformed(evt);
            }
        });

        btnCreateBA.setText("Create Bank Account");
        btnCreateBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBAActionPerformed(evt);
            }
        });

        btnViewBA.setText("View Bank Account");
        btnViewBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnCreateN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateHA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewHA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateLA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewLA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateBA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewBA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblTitle)))
                .addGap(6, 6, 6))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateBA, btnCreateHA, btnCreateLA, btnCreateN, btnViewBA, btnViewHA, btnViewLA, btnViewN});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addComponent(btnCreateN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewN)
                .addGap(29, 29, 29)
                .addComponent(btnCreateHA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewHA)
                .addGap(32, 32, 32)
                .addComponent(btnCreateLA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewLA)
                .addGap(35, 35, 35)
                .addComponent(btnCreateBA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewBA)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreateBA, btnCreateHA, btnCreateLA, btnCreateN, btnViewBA, btnViewHA, btnViewLA, btnViewN});

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNActionPerformed
        // TODO add your handling code here:
        
        CreateJPanelN createPanel = new CreateJPanelN(log);
        splitPane.setRightComponent(createPanel);
        
    }//GEN-LAST:event_btnCreateNActionPerformed

    private void btnCreateHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHAActionPerformed
        // TODO add your handling code here:
      CreateJPanelHA createPanel = new CreateJPanelHA(halog);
      splitPane.setRightComponent(createPanel);
        
    }//GEN-LAST:event_btnCreateHAActionPerformed

    private void btnViewHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHAActionPerformed
        // TODO add your handling code here:
        ViewJPanelHA viewPanel = new ViewJPanelHA(halog);
      splitPane.setRightComponent(viewPanel);
        
        
    }//GEN-LAST:event_btnViewHAActionPerformed

    private void btnCreateLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLAActionPerformed
        // TODO add your handling code here:
        CreateJPanelLA createPanel = new CreateJPanelLA(lalog);
        splitPane.setRightComponent(createPanel);
        
     
    }//GEN-LAST:event_btnCreateLAActionPerformed

    private void btnViewLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLAActionPerformed
        // TODO add your handling code here:
        ViewJPanelLA viewPanel = new ViewJPanelLA(lalog);
        splitPane.setRightComponent(viewPanel);
        
    }//GEN-LAST:event_btnViewLAActionPerformed

    private void btnCreateBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBAActionPerformed
        // TODO add your handling code here:
        CreateJPanelDC createPanel = new CreateJPanelDC(register);
        splitPane.setRightComponent(createPanel); 
        
    }//GEN-LAST:event_btnCreateBAActionPerformed

    private void btnViewBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBAActionPerformed
        // TODO add your handling code here:
        ViewJPanelDC viewPanel = new ViewJPanelDC(register);
        splitPane.setRightComponent(viewPanel); 
    }//GEN-LAST:event_btnViewBAActionPerformed

    private void btnViewNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNActionPerformed
        // TODO add your handling code here:
        ViewJPanelN viewPanel = new ViewJPanelN(log);
        splitPane.setRightComponent(viewPanel);
        
    }//GEN-LAST:event_btnViewNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBA;
    private javax.swing.JButton btnCreateHA;
    private javax.swing.JButton btnCreateLA;
    private javax.swing.JButton btnCreateN;
    private javax.swing.JButton btnViewBA;
    private javax.swing.JButton btnViewHA;
    private javax.swing.JButton btnViewLA;
    private javax.swing.JButton btnViewN;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
