/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LocalAddressC;
import model.LocalAddressLog;

/**
 *
 * @author saitarunreddylakkireddy
 */
public class ViewJPanelLA extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanelLA
     */
    LocalAddressLog lalog;
    
    public ViewJPanelLA(LocalAddressLog lalog) {
        initComponents();
        this.lalog = lalog;
        
        populateAddresses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewLA = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblStreetAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZIP = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZIP = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLA = new javax.swing.JTable();
        btnViewLA = new javax.swing.JButton();
        btnDeleteLA = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 204));

        lblViewLA.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblViewLA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewLA.setText("View Local Address");

        lblName.setText("Name");

        lblStreetAddress.setText("Street Address");

        lblCity.setText("City");

        lblState.setText("State");

        lblZIP.setText("ZIP");

        txtZIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZIPActionPerformed(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        tblLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Street Address", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLA);

        btnViewLA.setText("View");
        btnViewLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLAActionPerformed(evt);
            }
        });

        btnDeleteLA.setText("Delete");
        btnDeleteLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewLA)
                        .addGap(64, 64, 64)
                        .addComponent(btnDeleteLA))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblViewLA, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCity)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblStreetAddress, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblState)
                            .addComponent(lblZIP))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZIP, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblViewLA)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewLA)
                    .addComponent(btnDeleteLA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZIP))
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtZIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZIPActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnViewLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLAActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblLA.getSelectedRow();
        if (selectedRowIndex<0) { 
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        
         DefaultTableModel model = (DefaultTableModel)   tblLA.getModel();
       LocalAddressC selectedAddress = (LocalAddressC) model.getValueAt(selectedRowIndex, 0);
       
        txtName.setText(selectedAddress.getName());
       txtStreetAddress.setText(selectedAddress.getStreetAddress());
       txtCity.setText(selectedAddress.getCity());
       txtState.setText(selectedAddress.getState());
       txtZIP.setText(selectedAddress.getZip());
       
        
    }//GEN-LAST:event_btnViewLAActionPerformed

    private void btnDeleteLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLAActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblLA.getSelectedRow();
        if (selectedRowIndex<0) { 
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
         DefaultTableModel model = (DefaultTableModel)   tblLA.getModel();
       LocalAddressC selectedAddress = (LocalAddressC) model.getValueAt(selectedRowIndex, 0);
       
         lalog.deleteAddress(selectedAddress);
        JOptionPane.showMessageDialog(this, "This Address has been deleted.");
        
        populateAddresses();
        
          txtName.setText("");
        txtStreetAddress.setText("");
        txtState.setText("");
        txtCity.setText("");
        txtZIP.setText(""); 
        
    }//GEN-LAST:event_btnDeleteLAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteLA;
    private javax.swing.JButton btnViewLA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblViewLA;
    private javax.swing.JLabel lblZIP;
    private javax.swing.JTable tblLA;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtZIP;
    // End of variables declaration//GEN-END:variables

    private void populateAddresses() {
    DefaultTableModel model = (DefaultTableModel) tblLA.getModel();
     model.setRowCount(0);    
     for (LocalAddressC vs : lalog.getLalog()) {
         Object[] row = new Object[3];
         row[0] = vs;
         row[1] = vs.getStreetAddress();
         row[2] = vs.getCity();
         
         model.addRow(row); 
    }
}
}
