/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BankDC;
import model.BankDLog;

/**
 *
 * @author saitarunreddylakkireddy
 */
public class ViewJPanelDC extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanelDC
     */
    BankDLog register;
    
    
    public ViewJPanelDC(BankDLog register) {
        initComponents();
        this.register = register; 
        
       populateDC();
       
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDC = new javax.swing.JTable();
        btnViewDC = new javax.swing.JButton();
        btnDeleteDC = new javax.swing.JButton();
        txtAccountType = new javax.swing.JTextField();
        txtCreditAmount = new javax.swing.JTextField();
        txtDebtAmount = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        lblDebtAmount = new javax.swing.JLabel();
        lblCreditAmount = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAccountNumber = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Bank Details");

        tblDC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "AccountNumber", "Account Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDC);

        btnViewDC.setText("View");
        btnViewDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDCActionPerformed(evt);
            }
        });

        btnDeleteDC.setText("Delete");
        btnDeleteDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDCActionPerformed(evt);
            }
        });

        txtAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountTypeActionPerformed(evt);
            }
        });

        txtCreditAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditAmountActionPerformed(evt);
            }
        });

        txtDebtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDebtAmountActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        lblAccountType.setText("Account Type");

        lblAccountNumber.setText("Account Number");

        lblDebtAmount.setText("Debt Amount");

        lblCreditAmount.setText("Credit Amount");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewDC)
                .addGap(54, 54, 54)
                .addComponent(btnDeleteDC)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccountNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAccountType, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCreditAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDebtAmount, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDebtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteDC)
                    .addComponent(btnViewDC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber)
                    .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType)
                    .addComponent(txtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDebtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDebtAmount))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountTypeActionPerformed

    private void txtCreditAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditAmountActionPerformed

    private void txtDebtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDebtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDebtAmountActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNumberActionPerformed

    private void btnDeleteDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDCActionPerformed
        // TODO add your handling code here:
        
          int selectedRowIndex = tblDC.getSelectedRow();
        if (selectedRowIndex<0) { 
           
            JOptionPane.showMessageDialog(this, "Please select an account to delete.");
            return;
            
        }
            DefaultTableModel model = (DefaultTableModel)   tblDC.getModel();
        
         BankDC selectedAccount = (BankDC) model.getValueAt(selectedRowIndex, 0); 
         
         
         register.deleteAccount(selectedAccount);
         JOptionPane.showMessageDialog(this, "This Account has been deleted.");
    
         populateDC();
         
         txtName.setText("");
         txtAccountNumber.setText("");
         txtAccountType.setText("");
         txtDebtAmount.setText("");
         txtCreditAmount.setText("");
            
    }//GEN-LAST:event_btnDeleteDCActionPerformed

    private void btnViewDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDCActionPerformed
        // TODO add your handling code here:
          int selectedRowIndex = tblDC.getSelectedRow();
        if (selectedRowIndex<0) { 
           
            JOptionPane.showMessageDialog(this, "Please select an account to View.");
            return;
            
        }
            DefaultTableModel model = (DefaultTableModel)   tblDC.getModel();
        
         BankDC selectedAccount = (BankDC) model.getValueAt(selectedRowIndex, 0); 
         
        txtName.setText(selectedAccount.getName());
        txtAccountNumber.setText(selectedAccount.getAccountNumber());
        txtAccountType.setText(selectedAccount.getAccountType());
        txtDebtAmount.setText(selectedAccount.getDebtAmount());
        txtCreditAmount.setText(selectedAccount.getCreditAmount());
        
 
        
        
       
         
    }//GEN-LAST:event_btnViewDCActionPerformed
         
         
         
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteDC;
    private javax.swing.JButton btnViewDC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblCreditAmount;
    private javax.swing.JLabel lblDebtAmount;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblDC;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtAccountType;
    private javax.swing.JTextField txtCreditAmount;
    private javax.swing.JTextField txtDebtAmount;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables


    private void populateDC() {
    DefaultTableModel model = (DefaultTableModel)   tblDC.getModel();
        model.setRowCount(0);
        for (BankDC vs : register.getRegister()) {

            Object[] row = new Object[3];
            row[0] = vs;
            row[1] = vs.getAccountNumber();
            row[2] = vs.getAccountType();

            model.addRow(row);

     }    
    
    }
}
