/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import javax.swing.JPanel;
import ucode.Business;
import ucode.UserAccounts.UserAccount;

/**
 *
 * @author marri
 */
public class MetricsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MetricsJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    //UserAccount selecteduseraccount;

    public MetricsJPanel(Business bz, JPanel jp) {
        business = bz;
        CardSequencePanel = jp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
