/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GraduationAudit;

import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ucode.Business;
import ucode.CourseCatalog.Course;
import ucode.CourseSchedule.CourseOffer;
import ucode.profiles.StudentProfile;

/**
 *
 * @author 
 */
public class EvaluatorworkareaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EvaluatorworkareaJPanel
     */
    JPanel CardSequencePanel;
    Business business; 
    StudentProfile selectedSP;
    //private StudentProfile sp;

    public EvaluatorworkareaJPanel(Business bz, JPanel jp) {
        this.business = bz;
        this.CardSequencePanel = jp;
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void refreshTable() {

        int rc = tbCourses.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tbCourses.getModel()).removeRow(i);
        }

        for (StudentProfile sp : business.getStudentDirectory().findStudentAppliedForGraduation()) {
            Object[] row = new Object[4];
            row[0] = sp;
            row[1] = sp.getTranscript().getRegisteredCourses().size();
            row[2] = sp.getTranscript().GetTotalStudentScore();
            row[3] = sp.getTranscript().isEligble();
            ((DefaultTableModel) tbCourses.getModel()).addRow(row);
        }
//        for (String sem : business.getSems()) {
//            ArrayList<CourseOffer> coList = business.getCourseSchedule(sem).getCourseSchedule();
//
//            for () ) {
//                if (co.findRegisteredStudent(sp) == null) {
//                    continue;
//                }
//                Object[] row = new Object[5];
//                row[0] = co; //.getAssociatedPersonProfile().getPerson().getName();
//                row[1] = sp.getTranscript().
//                row[2] = String.valueOf(sp.getTranscript().GetTotalStudentScore());
//                ((DefaultTableModel) tbCourses.getModel()).addRow(row);
//            }
//        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCourses = new javax.swing.JTable();
        btnGraduate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Audit Requests");
        add(jLabel1);
        jLabel1.setBounds(130, 30, 501, 22);

        tbCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "No of courses registered", "Grade", "isEligible"
            }
        ));
        tbCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbCoursesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbCourses);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 695, 190);

        btnGraduate.setText("Graduate");
        btnGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduateActionPerformed(evt);
            }
        });
        add(btnGraduate);
        btnGraduate.setBounds(230, 320, 130, 23);

        jButton1.setText("Reject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(390, 320, 110, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void tbCoursesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCoursesMousePressed
        // TODO add your handling code here:
        // Extracts the row (uaser account) in the table that is selected by the user
        int size = tbCourses.getRowCount();
        int selectedrow = tbCourses.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selectedSP = (StudentProfile) tbCourses.getValueAt(selectedrow, 0);
        if (selectedSP == null) {
            return;
        }

    }//GEN-LAST:event_tbCoursesMousePressed

    private void btnGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduateActionPerformed
        // TODO add your handling code here:
        selectedSP.setGraduated(true);
        selectedSP.graduateRequestRejected();
        refreshTable();
    }//GEN-LAST:event_btnGraduateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selectedSP.setGraduated(false);
        selectedSP.graduateRequestRejected();
        refreshTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraduate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCourses;
    // End of variables declaration//GEN-END:variables
}
