 
package UserInterface.WorkAreas.FacultyRole;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ucode.Business;
import ucode.CourseCatalog.Course;
import ucode.profiles.FacultyAssignment;
import ucode.profiles.FacultyProfile;

/**
 *
 * @author 
 */
public class AddCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCourseJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    FacultyProfile fp;
    ManageCoursesJPanel mcjp;

    public AddCourseJPanel(Business bz, FacultyProfile facultyProfile, JPanel jp, ManageCoursesJPanel mcjp) {
        CardSequencePanel = jp;
        business = bz;
        fp = facultyProfile;
        this.mcjp = mcjp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        lblNumber = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setAutoscrolls(true);
        setLayout(null);

        btnCreate.setText("ADD Course");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(240, 250, 130, 20);

        lblNumber.setText("Course Code");
        add(lblNumber);
        lblNumber.setBounds(180, 140, 90, 20);

        lblCredits.setText("Credit Hours");
        add(lblCredits);
        lblCredits.setBounds(180, 190, 90, 17);

        lblName.setText("Name");
        add(lblName);
        lblName.setBounds(180, 90, 60, 17);
        add(txtNumber);
        txtNumber.setBounds(290, 140, 100, 23);
        add(txtCredits);
        txtCredits.setBounds(290, 180, 100, 23);
        add(txtName);
        txtName.setBounds(290, 90, 100, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Course");
        add(jLabel1);
        jLabel1.setBounds(0, 6, 640, 40);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(60, 300, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().isBlank() || txtCredits.getText().isBlank() || txtNumber.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please fill all the details!");
            return;
        }
        FacultyAssignment fa = fp.AssignAsTeacher();
        if (business.getCourseCatalog().newCourse(txtName.getText(), txtNumber.getText(), Integer.parseInt(txtCredits.getText()), fa) == null) {
            JOptionPane.showMessageDialog(this, "Course number not available!");
            return;
        }
        JOptionPane.showMessageDialog(this, "Course created successfully!");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        mcjp.refreshTable();
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
