
package UserInterface.WorkAreas.FacultyRole;

import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.*;
import javax.swing.JOptionPane;
import ucode.Business;

import javax.swing.JPanel;
import ucode.CourseCatalog.Course;

/**
 *
 * @author 
 */
public class EditCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Course selectedCourse;
    ManageCoursesJPanel mcjp;
    String originalCoureNumber;

    public EditCourseJPanel(Business bz, Course sc, JPanel jp, ManageCoursesJPanel mcjp) {
        this.mcjp = mcjp;
        CardSequencePanel = jp;
        this.business = bz;
        selectedCourse = sc;
        initComponents();
        prefill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCredits = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(20, 310, 80, 23);

        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(500, 310, 80, 23);

        jLabel1.setText("Credit Hours");
        add(jLabel1);
        jLabel1.setBounds(80, 130, 190, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Edit Course");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        jLabel3.setText("Course Code");
        add(jLabel3);
        jLabel3.setBounds(80, 170, 190, 20);

        jLabel4.setText("Rate per Credit Hour");
        add(jLabel4);
        jLabel4.setBounds(80, 220, 160, 17);

        jLabel5.setText("Name");
        add(jLabel5);
        jLabel5.setBounds(80, 90, 190, 17);
        add(txtCredits);
        txtCredits.setBounds(290, 130, 70, 23);
        add(txtNumber);
        txtNumber.setBounds(290, 180, 70, 23);
        add(txtPrice);
        txtPrice.setBounds(290, 220, 70, 23);
        add(txtName);
        txtName.setBounds(290, 90, 70, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        mcjp.refreshTable();
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    public void prefill() {
        originalCoureNumber = selectedCourse.getCourseNumber();
        txtCredits.setText(String.valueOf(selectedCourse.getCredits()));
        txtName.setText(selectedCourse.getName());
        txtNumber.setText(originalCoureNumber);
        txtPrice.setText(String.valueOf(selectedCourse.getPrice()));

    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtCredits.getText().isBlank() || txtName.getText().isBlank() || txtNumber.getText().isBlank() || txtPrice.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "please fill all the fields");
            return;
        }
        if (!originalCoureNumber.equals(txtNumber.getText())) {
            if (business.getCourseCatalog().getCourseByNumber(txtNumber.getText()) != null) {
                JOptionPane.showMessageDialog(this, "course number not available, it needs to be unique!");
                return;
            }
        }

        selectedCourse.setCredits(Integer.parseInt(txtCredits.getText()));
        selectedCourse.setName(txtName.getText());
        selectedCourse.setNumber(txtNumber.getText());
        selectedCourse.setPrice(Integer.parseInt(txtPrice.getText()));
        JOptionPane.showMessageDialog(this, "Course updated successfully!");
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

}
