/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ucode.Business;
import ucode.profiles.FacultyProfile;

/**
 *
 * @author marri
 */
public class ReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportsJPanel
     */
    JPanel CardSequencePanel;
    Business business;

    FacultyProfile fp;

    public ReportsJPanel(Business bz, FacultyProfile facultyProfile, JPanel jp) {
        CardSequencePanel = jp;
        fp = facultyProfile;
        this.business = bz;
        initComponents();
        // business.getCourseSchedule(dropSem.getSelectedItem().toString()).getCoursesList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropSem = new javax.swing.JComboBox<>();
        dropCourseOffer = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblStudents = new javax.swing.JLabel();
        lblRevenue = new javax.swing.JLabel();
        txtStudents = new javax.swing.JTextField();
        txtRevenue = new javax.swing.JTextField();
        lblRevenue1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        dropSem.setModel(new javax.swing.DefaultComboBoxModel<>(business.getSems()));
        dropSem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dropSemItemStateChanged(evt);
            }
        });
        add(dropSem);
        dropSem.setBounds(92, 50, 72, 23);

        dropCourseOffer.setModel(new javax.swing.DefaultComboBoxModel<>(business.getCourseSchedule(dropSem.getSelectedItem().toString()).getCoursesListForProf(fp.getPerson().getId())));
        add(dropCourseOffer);
        dropCourseOffer.setBounds(250, 50, 72, 23);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(420, 50, 72, 23);

        jLabel1.setText("Semester");
        add(jLabel1);
        jLabel1.setBounds(25, 53, 60, 17);

        jLabel2.setText("Course");
        add(jLabel2);
        jLabel2.setBounds(200, 50, 41, 17);

        lblStudents.setText("No Of Students");
        add(lblStudents);
        lblStudents.setBounds(78, 117, 111, 32);

        lblRevenue.setText("Course Revenue");
        add(lblRevenue);
        lblRevenue.setBounds(78, 176, 111, 32);
        add(txtStudents);
        txtStudents.setBounds(250, 122, 84, 23);
        add(txtRevenue);
        txtRevenue.setBounds(250, 181, 84, 23);

        lblRevenue1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRevenue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevenue1.setText("Reports");
        add(lblRevenue1);
        lblRevenue1.setBounds(0, 0, 593, 38);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(50, 320, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (dropSem.getSelectedItem() == null || dropCourseOffer.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select filters!");
            return;
        }
//        if (dropSem != null && dropCourseOffer
//                == null) {
//            txtRevenue.setText(String.valueOf(business.getCourseSchedule(dropSem.getSelectedItem().toString()).calculateTotalRevenues()));
//        }else{
        txtRevenue.setText(String.valueOf(business.getCourseSchedule(dropSem.getSelectedItem().toString()).getCourseOfferByNumber(dropCourseOffer.getSelectedItem().toString()).getTotalCourseRevenues()));
        txtStudents.setText(String.valueOf(business.getCourseSchedule(dropSem.getSelectedItem().toString()).getCourseOfferByNumber(dropCourseOffer.getSelectedItem().toString()).getStudents().size()));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void dropSemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dropSemItemStateChanged
        // TODO add your handling code here:
        dropCourseOffer.setModel(new javax.swing.DefaultComboBoxModel<>(business.getCourseSchedule(dropSem.getSelectedItem().toString()).getCoursesListForProf(fp.getPerson().getId())));
    }//GEN-LAST:event_dropSemItemStateChanged

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> dropCourseOffer;
    private javax.swing.JComboBox<String> dropSem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JLabel lblRevenue1;
    private javax.swing.JLabel lblStudents;
    private javax.swing.JTextField txtRevenue;
    private javax.swing.JTextField txtStudents;
    // End of variables declaration//GEN-END:variables
}
